/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ea3858",
        "surface-variant": "#262626",
        "surface-container-low": "#131313",
        "error": "#ee7d77",
        "inverse-surface": "#fcf8f8",
        "on-secondary-container": "#bbbfc9",
        "secondary-fixed": "#dee3ec",
        "outline-variant": "#484848",
        "secondary": "#999ea7",
        "tertiary": "#ff6f7e",
        "on-secondary": "#1b2128",
        "background": "#0e0e0e",
        "primary": "#bdc2ff",
        "secondary-container": "#373c43",
        "primary-dim": "#acb3ff",
        "on-tertiary-fixed": "#000000",
        "inverse-primary": "#4854bb",
        "on-error-container": "#ff9993",
        "primary-fixed": "#dfe0ff",
        "on-tertiary-container": "#100001",
        "surface-container-high": "#1f2020",
        "tertiary-container": "#fc4563",
        "surface-bright": "#2c2c2c",
        "surface-container": "#191a1a",
        "on-error": "#490106",
        "on-background": "#e7e5e4",
        "on-primary-fixed": "#26329a",
        "surface-tint": "#bdc2ff",
        "secondary-dim": "#999ea7",
        "primary-fixed-dim": "#ced1ff",
        "error-dim": "#bb5551",
        "surface-container-lowest": "#000000",
        "surface-dim": "#0e0e0e",
        "inverse-on-surface": "#565554",
        "tertiary-fixed": "#fc4563",
        "on-secondary-fixed-variant": "#575c64",
        "on-tertiary-fixed-variant": "#340009",
        "primary-container": "#2e3aa2",
        "on-tertiary": "#490010",
        "on-surface-variant": "#acabaa",
        "on-primary": "#27339b",
        "secondary-fixed-dim": "#d0d4de",
        "on-secondary-fixed": "#3a4047",
        "tertiary-dim": "#ff6f7e",
        "on-primary-container": "#c9cdff",
        "surface": "#0e0e0e",
        "outline": "#767575",
        "on-surface": "#e7e5e4",
        "surface-container-highest": "#262626",
        "on-primary-fixed-variant": "#4551b8",
        "error-container": "#7f2927"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [require('@tailwindcss/forms')],
}